name: 'build-test'
on:
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test-caching:
    name: Get latest linux amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          repository: KeisukeYamashita/setup-release-test-repo-public
      - uses: ./
        id: second-setup
        with:
          repository: KeisukeYamashita/setup-release-test-repo-public
      - name: Checked catched or not
        if: steps.second-setup.outputs.restore-from-cache == 'false'
        run: exit 1
  test-latest-linux-amd64:
    name: Get latest linux amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          repository: KeisukeYamashita/setup-release-test-repo-public
      - run: setup-release-test-repo-public
  test-tagged-linux-amd64:
    name: Get v0.1.0 linux amd64
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          repository: KeisukeYamashita/setup-release-test-repo-public
          tag: v0.1.0
      - run: setup-release-test-repo-public
  test-multiple-install:
    name: Get latest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          repository: KeisukeYamashita/setup-release-test-repo-public
      - uses: ./
        with:
          repository: KeisukeYamashita/setup-release-test-repo-public
  test-private:
    name: Get Private repository release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        with:
          repository: KeisukeYamashita/setup-release-test-repo-private
          token: ${{ secrets.SETUP_RELEASE_GITHUB_TOKEN }}
      - run: setup-release-test-repo-private
